import { StyleSheet } from "react-native";
import { Dimensions } from "react-native";

const SCREEN_HEIGHT = Dimensions.get("window").height;
const SCREEN_WIDTH = Dimensions.get("window").width;
const CARD_WIDTH = SCREEN_WIDTH * 0.8;
const CARD_HEIGHT = SCREEN_HEIGHT * 0.5;
const mainBackgroundColor = "#f6f6f6";
const primaryFont = "Palatino";
const fontSizeInput = 20;
const fontSizeButton = 10;
const fontSizeLinks = 10;
const fontSizeCategories = 10;
const fontWeightInput = "300";
const fontWeightButton = "500";
const fontWeightCategories = "500";
const borderRadiusInput = "10";
const borderRadiusButton = "10";

const styles = StyleSheet.create({
  primaryContainer: {
    backgroundColor: mainBackgroundColor,
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    marginHorizontal: "auto",
    position: "relative",
    width: "100%",
    maxWidth: 600,
    height: "100%",
    maxHeight: 900,
    minHeight: 600,
    paddingTop: 20,
  },

  formContainer: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "top",
    alignItems: "center",
    minWidth: 300,
    minHeight: 400,
  },
  loginForm: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "top",
    alignItems: "center",
  },
  roomsContainer: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "top",
    alignItems: "center",
    position: "relative",
    zIndex: 2,
  },
  startPageContainer: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "top",
    alignItems: "center",
    position: "relative",
    zIndex: 2,
  },
  categoryContainer: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    maxWidth: "95%",
    maxHeight: "95%",
    borderColor: "#ccc",
    borderWidth: 2,
    shadowColor: "#ccc",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
    padding: 10,
  },
  StartDisplayContainer: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "top",
    alignItems: "center",
    position: "relative",
  },
  countdownContainer: {
    flex: 1,
    flexDirection: "column",
    justifyContent: "top",
    alignItems: "center",
    position: "relative",
  },
  banner: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 50,
  },
  logo: {
    width: 300,
    height: 100,
  },
  inputField: {
    height: 50,
    width: 300,
    fontSize: fontSizeInput,
    fontWeight: fontWeightInput,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginVertical: 10,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 15,
  },
  errorAlert: {},
  btnContainer: {
    maxHeight: 100,
    width: 300,
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  btnContainerWidget: {
    width: 250,
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  btnContainerMode: {
    width: 250,
    maxHeight: 100,
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  largeBtn: {
    width: "100%",
  },
  returnBtn: {
    backgroundColor: mainBackgroundColor,
    position: "relative",
    paddingLeft: 300,
  },
  roomsBtn: {
    minWidth: "85%",
    marginBottom: 40,
  },
  recentRoomsTitle: {
    minWidth: "85%",
  },
  categoryBtn: {
    margin: 2,
  },
  startBtn: {},
  categorySubmitBtn: {
    margin: 5,
    marginTop: 30,
    minWidth: "35%",
  },
  hideMainRoomDisplay: {
    display: "none",
  },
  recentRoomsWidget: {
    minWidth: "85%",
    minHeight: 300,
    borderColor: "#ccc",
    borderWidth: 1,
    shadowColor: "#ccc",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
  },
  recentRoomsBtnContainer: {
    height: "100%",
    width: "100%",
  },
  recentRoomsBtn: {
    flex: 1,
    height: "20%",
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    justifyContent: "center",
    padding: 20,
    margin: 2,
    shadowColor: "#ccc",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
  },
  recentRoomsName: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 5,
  },
  recentRoomsCode: {
    fontSize: 16,
    color: "#aaa",
  },
  widgetHeading: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 8,
  },
  roomWidgets: {
    position: "absolute",
    zIndex: 10,
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    marginHorizontal: "auto",
    padding: 20,
    minWidth: "85%",
    minHeight: 200,
    borderColor: "#ccc",
    borderWidth: 1,
    shadowColor: "#ccc",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
  },
  hideWidget: {
    display: "none",
  },
  roomCodeText: {
    fontSize: 45,
    color: "red",
    minWidth: "80%",
    textAlign: "center",
    shadowColor: "#ccc",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
    borderColor: "#ccc",
    borderWidth: 1,
  },
  countdownTimerContainer: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    maxWidth: "100%",
    maxHeight: "90%",
  },
  countdownTimer: {
    fontSize: 400,
    fontWeight: "bold",
  },
  swipeScreenContainer: {
    flex: 1,
    backgroundColor: "#fff",
  },
  deckContainer: {
    flex: 5,
    alignItems: "center",
  },
  cardStyle: {
    position: "absolute",
    width: SCREEN_WIDTH * 0.8,
    height: SCREEN_HEIGHT * 0.5,
    borderRadius: 10,
    padding: 2,
    backgroundColor: "#f6f6f6",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#f6f6f6",
    shadowColor: "#f6f6f6",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 5,
  },
  deckTextStyle: {
    fontSize: 32,
    fontWeight: "bold",
    textAlign: "center",
    margin: 10,
  },
  deckImageStyle: {
    height: "100%",
    width: "100%",
    borderRadius: 10,
  },
  circleContainerLeft: {
    height: 65,
    width: 65,
    backgroundColor: "#fff",
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 20,
    left: "10%",
  },
  circleContainerRight: {
    height: 65,
    width: 65,
    backgroundColor: "#fff",
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 20,
    right: "10%",
  },
  circleContainerCenter: {
    height: 65,
    width: 65,
    backgroundColor: "#fff",
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 20,
    left: "43%", // 43% makes it look like in center
  },
  matchBarContainer: {
    flex: 0.5,
    alignItems: "center",
    justifyContent: "space-around",
    flexDirection: "row",
  },
  matchBarIcon: {
    height: 35,
    width: 35,
    resizeMode: "contain",
  },
  scrollContainer: {
    flexGrow: 1,
    alignItems: "center",
  },
  matchesContainer: {
    flex: 1,
    backgroundColor: "#f6f6f6",
    paddingTop: 20,
  },
  matchWidgetTitle: {
    fontSize: 24,
    fontWeight: "bold",
    marginVertical: 20,
    textAlign: "center",
  },
  matchWidgetMovieContainer: {
    width: "90%",
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  matchWidgetMovieImage: {
    width: 80,
    height: 100,
    resizeMode: "contain",
    marginRight: 20,
    borderRadius: 10,
  },
  matchWidgetMovieDetails: {
    flex: 1,
  },
  matchWidgetMovieTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 5,
  },
  matchWidgetLikes: {
    fontSize: 16,
    color: "#999999",
  },
  toolbarContainer: {
    flex: 1,
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    marginTop: 50,
    alignItems: "center",
    flexDirection: "row",
    maxHeight: 30,
    width: "100%",
    paddingHorizontal: 20,
    justifyContent: "space-between",
    zIndex: 100,
  },
});

export default styles;
