export const categoriesArray = [
  { name: "Action", variant: "outlined", id: 0 },
  { name: "Adventure", variant: "outlined", id: 1 },
  { name: "Animation", variant: "outlined", id: 2 },
  { name: "Biography", variant: "outlined", id: 3 },
  { name: "Comedy", variant: "outlined", id: 4 },
  { name: "Crime", variant: "outlined", id: 5 },
  { name: "Documentary", variant: "outlined", id: 6 },
  { name: "Drama", variant: "outlined", id: 7 },
  { name: "Family", variant: "outlined", id: 8 },
  { name: "Fantasy", variant: "outlined", id: 9 },
  { name: "Film Noir", variant: "outlined", id: 10 },
  { name: "Game Show", variant: "outlined", id: 11 },
  { name: "History", variant: "outlined", id: 12 },
  { name: "Horror", variant: "outlined", id: 13 },
  { name: "Music", variant: "outlined", id: 14 },
  { name: "Musical", variant: "outlined", id: 15 },
  { name: "Mystery", variant: "outlined", id: 16 },
  { name: "News", variant: "outlined", id: 17 },
  { name: "Reality TV", variant: "outlined", id: 18 },
  { name: "Romance", variant: "outlined", id: 19 },
  { name: "Sci-Fi", variant: "outlined", id: 20 },
  { name: "Sport", variant: "outlined", id: 21 },
  { name: "Talk-Show", variant: "outlined", id: 22 },
  { name: "Thriller", variant: "outlined", id: 23 },
  { name: "War", variant: "outlined", id: 24 },
  { name: "Western", variant: "outlined", id: 25 },
];
